#include "ScriptMgr.h"
#include "siege_of_orgrimmar.h"

struct SpoilsOfPandaria
{
	uint32 crate;
	float X, Y;
};

SpoilsOfPandaria spoilsOfPandaria[] =
{
	{ 0, 0.0f, 0.0f }
	//// North-East
	//{ GOB_PANDAREN_CRATE, 0.0f, 0.0f },
	//{ GOB_PANDAREN_CRATE, 0.0f, 0.0f },

	//{ GOB_MOGU_MASSIVE_CRATE, 0.0f, 0.0f },
	//{ GOB_MOGU_MASSIVE_CRATE, 0.0f, 0.0f },

	//{ GOB_MOGU_STOUT_CRATE, 0.0f, 0.0f },
	//{ GOB_MOGU_STOUT_CRATE, 0.0f, 0.0f },
	//{ GOB_MOGU_STOUT_CRATE, 0.0f, 0.0f },
	//{ GOB_MOGU_STOUT_CRATE, 0.0f, 0.0f },
	//{ GOB_MOGU_STOUT_CRATE, 0.0f, 0.0f },
	//{ GOB_MOGU_STOUT_CRATE, 0.0f, 0.0f },

	//{ GOB_MOGU_LIGHTWEIGHT_CRATE, 0.0f, 0.0f },
	//{ GOB_MOGU_LIGHTWEIGHT_CRATE, 0.0f, 0.0f },
	//{ GOB_MOGU_LIGHTWEIGHT_CRATE, 0.0f, 0.0f },
	//{ GOB_MOGU_LIGHTWEIGHT_CRATE, 0.0f, 0.0f },
	//{ GOB_MOGU_LIGHTWEIGHT_CRATE, 0.0f, 0.0f },
	//{ GOB_MOGU_LIGHTWEIGHT_CRATE, 0.0f, 0.0f },
	//{ GOB_MOGU_LIGHTWEIGHT_CRATE, 0.0f, 0.0f },
	//{ GOB_MOGU_LIGHTWEIGHT_CRATE, 0.0f, 0.0f },
	//{ GOB_MOGU_LIGHTWEIGHT_CRATE, 0.0f, 0.0f },
	//{ GOB_MOGU_LIGHTWEIGHT_CRATE, 0.0f, 0.0f },
	//{ GOB_MOGU_LIGHTWEIGHT_CRATE, 0.0f, 0.0f },
	//{ GOB_MOGU_LIGHTWEIGHT_CRATE, 0.0f, 0.0f },
	//{ GOB_MOGU_LIGHTWEIGHT_CRATE, 0.0f, 0.0f },
	//{ GOB_MOGU_LIGHTWEIGHT_CRATE, 0.0f, 0.0f },
	//{ GOB_MOGU_LIGHTWEIGHT_CRATE, 0.0f, 0.0f },
	//{ GOB_MOGU_LIGHTWEIGHT_CRATE, 0.0f, 0.0f },
	//{ GOB_MOGU_LIGHTWEIGHT_CRATE, 0.0f, 0.0f },
	//{ GOB_MOGU_LIGHTWEIGHT_CRATE, 0.0f, 0.0f },


	//// South-East
	//{ GOB_PANDAREN_CRATE, 0.0f, 0.0f },
	//{ GOB_PANDAREN_CRATE, 0.0f, 0.0f },

	//{ GOB_MOGU_MASSIVE_CRATE, 0.0f, 0.0f },
	//{ GOB_MOGU_MASSIVE_CRATE, 0.0f, 0.0f },

	//{ GOB_MOGU_STOUT_CRATE, 0.0f, 0.0f },
	//{ GOB_MOGU_STOUT_CRATE, 0.0f, 0.0f },
	//{ GOB_MOGU_STOUT_CRATE, 0.0f, 0.0f },
	//{ GOB_MOGU_STOUT_CRATE, 0.0f, 0.0f },
	//{ GOB_MOGU_STOUT_CRATE, 0.0f, 0.0f },
	//{ GOB_MOGU_STOUT_CRATE, 0.0f, 0.0f },

	//{ GOB_MOGU_LIGHTWEIGHT_CRATE, 0.0f, 0.0f },
	//{ GOB_MOGU_LIGHTWEIGHT_CRATE, 0.0f, 0.0f },
	//{ GOB_MOGU_LIGHTWEIGHT_CRATE, 0.0f, 0.0f },
	//{ GOB_MOGU_LIGHTWEIGHT_CRATE, 0.0f, 0.0f },
	//{ GOB_MOGU_LIGHTWEIGHT_CRATE, 0.0f, 0.0f },
	//{ GOB_MOGU_LIGHTWEIGHT_CRATE, 0.0f, 0.0f },
	//{ GOB_MOGU_LIGHTWEIGHT_CRATE, 0.0f, 0.0f },
	//{ GOB_MOGU_LIGHTWEIGHT_CRATE, 0.0f, 0.0f },
	//{ GOB_MOGU_LIGHTWEIGHT_CRATE, 0.0f, 0.0f },
	//{ GOB_MOGU_LIGHTWEIGHT_CRATE, 0.0f, 0.0f },
	//{ GOB_MOGU_LIGHTWEIGHT_CRATE, 0.0f, 0.0f },
	//{ GOB_MOGU_LIGHTWEIGHT_CRATE, 0.0f, 0.0f },
	//{ GOB_MOGU_LIGHTWEIGHT_CRATE, 0.0f, 0.0f },
	//{ GOB_MOGU_LIGHTWEIGHT_CRATE, 0.0f, 0.0f },
	//{ GOB_MOGU_LIGHTWEIGHT_CRATE, 0.0f, 0.0f },
	//{ GOB_MOGU_LIGHTWEIGHT_CRATE, 0.0f, 0.0f },
	//{ GOB_MOGU_LIGHTWEIGHT_CRATE, 0.0f, 0.0f },
	//{ GOB_MOGU_LIGHTWEIGHT_CRATE, 0.0f, 0.0f },

	//// North-West
	//{ GOB_PANDAREN_CRATE, 0.0f, 0.0f },
	//{ GOB_PANDAREN_CRATE, 0.0f, 0.0f },

	//{ GOB_MANTID_MASSIVE_CRATE, 0.0f, 0.0f },
	//{ GOB_MANTID_MASSIVE_CRATE, 0.0f, 0.0f },

	//{ GOB_MANTID_STOUT_CRATE, 0.0f, 0.0f },
	//{ GOB_MANTID_STOUT_CRATE, 0.0f, 0.0f },
	//{ GOB_MANTID_STOUT_CRATE, 0.0f, 0.0f },
	//{ GOB_MANTID_STOUT_CRATE, 0.0f, 0.0f },
	//{ GOB_MANTID_STOUT_CRATE, 0.0f, 0.0f },
	//{ GOB_MANTID_STOUT_CRATE, 0.0f, 0.0f },

	//{ GOB_MANTID_LIGHTWEIGHT_CRATE, 0.0f, 0.0f },
	//{ GOB_MANTID_LIGHTWEIGHT_CRATE, 0.0f, 0.0f },
	//{ GOB_MANTID_LIGHTWEIGHT_CRATE, 0.0f, 0.0f },
	//{ GOB_MANTID_LIGHTWEIGHT_CRATE, 0.0f, 0.0f },
	//{ GOB_MANTID_LIGHTWEIGHT_CRATE, 0.0f, 0.0f },
	//{ GOB_MANTID_LIGHTWEIGHT_CRATE, 0.0f, 0.0f },
	//{ GOB_MANTID_LIGHTWEIGHT_CRATE, 0.0f, 0.0f },
	//{ GOB_MANTID_LIGHTWEIGHT_CRATE, 0.0f, 0.0f },
	//{ GOB_MANTID_LIGHTWEIGHT_CRATE, 0.0f, 0.0f },
	//{ GOB_MANTID_LIGHTWEIGHT_CRATE, 0.0f, 0.0f },
	//{ GOB_MANTID_LIGHTWEIGHT_CRATE, 0.0f, 0.0f },
	//{ GOB_MANTID_LIGHTWEIGHT_CRATE, 0.0f, 0.0f },
	//{ GOB_MANTID_LIGHTWEIGHT_CRATE, 0.0f, 0.0f },
	//{ GOB_MANTID_LIGHTWEIGHT_CRATE, 0.0f, 0.0f },
	//{ GOB_MANTID_LIGHTWEIGHT_CRATE, 0.0f, 0.0f },
	//{ GOB_MANTID_LIGHTWEIGHT_CRATE, 0.0f, 0.0f },
	//{ GOB_MANTID_LIGHTWEIGHT_CRATE, 0.0f, 0.0f },
	//{ GOB_MANTID_LIGHTWEIGHT_CRATE, 0.0f, 0.0f },

	//// South-West
	//{ GOB_PANDAREN_CRATE, 0.0f, 0.0f },
	//{ GOB_PANDAREN_CRATE, 0.0f, 0.0f },

	//{ GOB_MANTID_MASSIVE_CRATE, 0.0f, 0.0f },
	//{ GOB_MANTID_MASSIVE_CRATE, 0.0f, 0.0f },

	//{ GOB_MANTID_STOUT_CRATE, 0.0f, 0.0f },
	//{ GOB_MANTID_STOUT_CRATE, 0.0f, 0.0f },
	//{ GOB_MANTID_STOUT_CRATE, 0.0f, 0.0f },
	//{ GOB_MANTID_STOUT_CRATE, 0.0f, 0.0f },
	//{ GOB_MANTID_STOUT_CRATE, 0.0f, 0.0f },
	//{ GOB_MANTID_STOUT_CRATE, 0.0f, 0.0f },

	//{ GOB_MANTID_LIGHTWEIGHT_CRATE, 0.0f, 0.0f },
	//{ GOB_MANTID_LIGHTWEIGHT_CRATE, 0.0f, 0.0f },
	//{ GOB_MANTID_LIGHTWEIGHT_CRATE, 0.0f, 0.0f },
	//{ GOB_MANTID_LIGHTWEIGHT_CRATE, 0.0f, 0.0f },
	//{ GOB_MANTID_LIGHTWEIGHT_CRATE, 0.0f, 0.0f },
	//{ GOB_MANTID_LIGHTWEIGHT_CRATE, 0.0f, 0.0f },
	//{ GOB_MANTID_LIGHTWEIGHT_CRATE, 0.0f, 0.0f },
	//{ GOB_MANTID_LIGHTWEIGHT_CRATE, 0.0f, 0.0f },
	//{ GOB_MANTID_LIGHTWEIGHT_CRATE, 0.0f, 0.0f },
	//{ GOB_MANTID_LIGHTWEIGHT_CRATE, 0.0f, 0.0f },
	//{ GOB_MANTID_LIGHTWEIGHT_CRATE, 0.0f, 0.0f },
	//{ GOB_MANTID_LIGHTWEIGHT_CRATE, 0.0f, 0.0f },
	//{ GOB_MANTID_LIGHTWEIGHT_CRATE, 0.0f, 0.0f },
	//{ GOB_MANTID_LIGHTWEIGHT_CRATE, 0.0f, 0.0f },
	//{ GOB_MANTID_LIGHTWEIGHT_CRATE, 0.0f, 0.0f },
	//{ GOB_MANTID_LIGHTWEIGHT_CRATE, 0.0f, 0.0f },
	//{ GOB_MANTID_LIGHTWEIGHT_CRATE, 0.0f, 0.0f },
	//{ GOB_MANTID_LIGHTWEIGHT_CRATE, 0.0f, 0.0f },
};

void AddSC_boss_spoils_of_pandaria()
{
}
